export const ETICARET_PLATFORMS = [
  {
    id: "trendyol",
    name: "Trendyol",
    icon: "🛒",
    titleFormat: "Marka + Model + Ana Özellik + Renk",
    maxTitleLength: 150,
    descMaxLength: 2000,
    tips: ["SEO için anahtar kelime tekrarı önemli", "Renk ve beden mutlaka belirtin", "Ürün özelliklerini madde madde yazın"],
  },
  {
    id: "hepsiburada",
    name: "Hepsiburada",
    icon: "🏪",
    titleFormat: "Marka Model - Özellik - Renk",
    maxTitleLength: 120,
    descMaxLength: 1500,
    tips: ["Kısa ve öz başlık tercih edin", "Teknik özellikleri vurgulayın"],
  },
  {
    id: "amazon",
    name: "Amazon TR",
    icon: "📦",
    titleFormat: "Brand + Product + Key Feature + Size/Color",
    maxTitleLength: 200,
    descMaxLength: 2000,
    tips: ["Bullet points kullanın", "A+ Content için uzun açıklama", "Anahtar kelimeleri doğal yerleştirin"],
  },
  {
    id: "n11",
    name: "n11",
    icon: "🔵",
    titleFormat: "Marka + Ürün Adı + Özellik",
    maxTitleLength: 150,
    descMaxLength: 1500,
    tips: ["SEO anahtar kelimeleri önemli", "Detaylı ürün açıklaması yazın"],
  },
  {
    id: "gittigidiyor",
    name: "GittiGidiyor",
    icon: "🟡",
    titleFormat: "Ürün Adı + Marka + Özellik",
    maxTitleLength: 140,
    descMaxLength: 1500,
    tips: ["Başlıkta anahtar kelime kullanın", "Ürün durumunu belirtin"],
  },
  {
    id: "ciceksepeti",
    name: "Çiçeksepeti",
    icon: "🌸",
    titleFormat: "Ürün Adı + Açıklama",
    maxTitleLength: 100,
    descMaxLength: 1000,
    tips: ["Hediye ürünlerde duygusal dil kullanın", "Teslimat bilgisi ekleyin"],
  },
  {
    id: "etsy",
    name: "Etsy",
    icon: "🧶",
    titleFormat: "Handmade + Product + Material + Style",
    maxTitleLength: 140,
    descMaxLength: 2000,
    tips: ["El yapımı vurgusunu öne çıkarın", "Hikaye anlatın", "Malzeme detayları verin"],
  },
  {
    id: "ebay",
    name: "eBay",
    icon: "🌐",
    titleFormat: "Brand + Model + Condition + Key Feature",
    maxTitleLength: 80,
    descMaxLength: 2000,
    tips: ["İngilizce anahtar kelimeler", "Durumu net belirtin", "Uluslararası kargo bilgisi"],
  },
  {
    id: "sahibinden",
    name: "Sahibinden",
    icon: "🏠",
    titleFormat: "Ürün Adı + Durum + Özellik",
    maxTitleLength: 100,
    descMaxLength: 2000,
    tips: ["Samimi dil kullanın", "Fiyat geçmişini belirtin", "İletişim bilgisi ekleyin"],
  },
  {
    id: "letgo",
    name: "Letgo/OfferUp",
    icon: "📱",
    titleFormat: "Ürün + Durum + Fiyat İpucu",
    maxTitleLength: 70,
    descMaxLength: 1000,
    tips: ["Kısa ve net", "Pazarlık durumunu belirtin"],
  },
  {
    id: "genel",
    name: "Genel E-Ticaret",
    icon: "🛍️",
    titleFormat: "Marka + Model + Özellik + Renk/Boyut",
    maxTitleLength: 150,
    descMaxLength: 2000,
    tips: ["SEO uyumlu başlık", "Detaylı açıklama", "Anahtar kelimeleri doğal kullanın"],
  },
] as const;

export type EticaretPlatform = (typeof ETICARET_PLATFORMS)[number];
